name: Pull Req Validation CI

on: 
  pull_request:
    branches:
      - main

jobs:
  validate:
    
    runs-on: ubuntu-latest

    steps: 
      
      -name: Checkout Code
      uses: actions/checkout@v4

      -name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version:18

      -name: Install Dependencies
      run: npm install

      -name: Run test
      run: npm test


